"""Generate docs/api.md from docs/openapi.json (run via `make api-docs`).

One section per endpoint: auth level, request, response, error codes and a curl example.
Hand-written notes (auth, errors) live in HEADER below; everything else comes from the schema.
"""

import json
import sys
from pathlib import Path
from typing import Any

BASE_URL = "http://localhost:8000"
EXAMPLES: dict[str, Any] = {
    "email": "you@example.com",
    "password": "a-long-password",
    "username": "alice_new",
    "display_name": "Alice",
    "title": "My first post",
    "body_md": "Hello **world**",
    "body": "Great post!",
}

HEADER = """# API reference (v1)

> Generated by `make api-docs` from [openapi.json](openapi.json) — do not edit by hand.
> Interactive version: http://localhost:8000/docs

## Authentication
Log in with `POST /api/v1/auth/login` (or register). The response sets an `access_token` cookie
(`HttpOnly`, `SameSite=Lax`, 24 h). Send it back on every request — browsers do this
automatically; with curl use a cookie jar:

```bash
curl -c cookies.txt -H 'Content-Type: application/json' \\
  -d '{"email":"alice@example.com","password":"demo-password-1"}' \\
  http://localhost:8000/api/v1/auth/login
curl -b cookies.txt http://localhost:8000/api/v1/auth/me
```

Auth levels used below:
- **public** — no login.
- **optional** — works logged out; personalised fields (`liked_by_me`, `is_owner`,
  `can_delete`) and your own drafts appear when logged in.
- **user** — login required (401 otherwise).
- **owner** — login required and you must own the resource (403 otherwise; 404 if it is
  someone else's draft, so drafts' existence never leaks).

## Errors
Every non-2xx response has the same envelope:

```json
{ "error": { "code": "POST_NOT_FOUND", "message": "Post not found", "details": null } }
```

| Status | Meaning | Example codes |
|---|---|---|
| 401 | Not logged in, or invalid credentials | `NOT_AUTHENTICATED`, `INVALID_CREDENTIALS` |
| 403 | Logged in but not allowed | `NOT_POST_OWNER`, `CANNOT_LIKE_OWN_POST`, `NOT_ALLOWED_TO_DELETE_COMMENT` |
| 404 | Missing **or not visible to you** | `POST_NOT_FOUND`, `COMMENT_NOT_FOUND`, `NOT_FOUND` |
| 409 | Uniqueness conflict (`details.field` names the field) | `EMAIL_TAKEN`, `USERNAME_TAKEN` |
| 422 | Validation failed (`details` = `[{field, message}]`) | `VALIDATION_ERROR` |

## Pagination
List endpoints take `?page=N` (1-based) and return
`{"items": [...], "page": 1, "page_size": 10, "total": 42}`. Posts: 10 per page; comments: 20.

## Endpoints
"""


def _ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def _type_of(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return f"`{_ref_name(schema['$ref'])}`"
    if "anyOf" in schema:
        parts = [_type_of(s) for s in schema["anyOf"]]
        return " \\| ".join(parts)
    if schema.get("type") == "array":
        return f"array of {_type_of(schema.get('items', {}))}"
    if "enum" in schema:
        return " \\| ".join(f"`{v}`" for v in schema["enum"])
    kind = schema.get("type", "object")
    fmt = schema.get("format")
    return f"{kind} ({fmt})" if fmt else str(kind)


def _constraints(schema: dict[str, Any]) -> str:
    notes = []
    for key, label in (("minLength", "min length"), ("maxLength", "max length")):
        if key in schema:
            notes.append(f"{label} {schema[key]}")
    for key, label in (("minimum", "≥"), ("maximum", "≤")):
        if key in schema:
            notes.append(f"{label} {schema[key]}")
    if "default" in schema:
        notes.append(f"default `{json.dumps(schema['default'])}`")
    return ", ".join(notes)


def _schema_table(name: str, schemas: dict[str, Any]) -> list[str]:
    schema = schemas.get(name, {})
    props: dict[str, Any] = schema.get("properties", {})
    if not props:
        return []
    required = set(schema.get("required", []))
    lines = [f"`{name}`:", "", "| Field | Type | Required | Notes |", "|---|---|---|---|"]
    for field, spec in props.items():
        notes = _constraints(spec) or spec.get("description", "")
        lines.append(
            f"| `{field}` | {_type_of(spec)} | {'yes' if field in required else 'no'} | {notes} |"
        )
    return [*lines, ""]


def _auth_level(op: dict[str, Any]) -> str:
    if not op.get("security"):
        return "public"
    responses = op.get("responses", {})
    if "403" in responses:
        return "owner"
    if "401" in responses:
        return "user"
    return "optional"


def _json_schema_ref(content: dict[str, Any]) -> str | None:
    schema = content.get("application/json", {}).get("schema", {})
    return _ref_name(schema["$ref"]) if "$ref" in schema else None


def _example_value(spec: dict[str, Any], field: str = "") -> Any:
    if field in EXAMPLES:
        return EXAMPLES[field]
    if "default" in spec:
        return spec["default"]
    if "enum" in spec:
        return spec["enum"][0]
    if "anyOf" in spec:
        return _example_value(next(s for s in spec["anyOf"] if s.get("type") != "null"))
    return {"integer": 1, "boolean": True}.get(spec.get("type", ""), "…")


def _curl(method: str, path: str, op: dict[str, Any], schemas: dict[str, Any]) -> str:
    auth = _auth_level(op)
    parts = ["curl"]
    if method != "get":
        parts.append(f"-X {method.upper()}")
    if auth != "public":
        parts.append("-b cookies.txt")
    body_ref = _json_schema_ref(op.get("requestBody", {}).get("content", {}))
    if body_ref:
        props = schemas.get(body_ref, {}).get("properties", {})
        required = set(schemas.get(body_ref, {}).get("required", []))
        example = {k: _example_value(v, k) for k, v in props.items() if k in required} or {
            k: _example_value(v, k) for k, v in list(props.items())[:1]
        }
        parts.append("-H 'Content-Type: application/json'")
        parts.append(f"-d '{json.dumps(example, ensure_ascii=False)}'")
    example_path = path.replace("{post_id}", "<post-id>").replace("{comment_id}", "<comment-id>")
    example_path = example_path.replace("{slug}", "<slug>")
    parts.append(f"{BASE_URL}{example_path}")
    return " ".join(parts)


def _endpoint(method: str, path: str, op: dict[str, Any], schemas: dict[str, Any]) -> list[str]:
    lines = [f"### {method.upper()} `{path}`", "", op.get("summary", ""), ""]
    lines.append(f"- **Auth:** {_auth_level(op)}")
    lines.append(f"- **Operation id:** `{op.get('operationId', '')}`")
    params = op.get("parameters", [])
    for param in params:
        if param.get("in") == "cookie":
            continue
        desc = param.get("description") or _constraints(param.get("schema", {}))
        lines.append(
            f"- **{param['in']} `{param['name']}`** ({_type_of(param.get('schema', {}))})"
            + (f": {desc}" if desc else "")
        )
    lines.append("")

    body_ref = _json_schema_ref(op.get("requestBody", {}).get("content", {}))
    if body_ref:
        lines += ["**Request body**", "", *_schema_table(body_ref, schemas)]

    responses: dict[str, Any] = op.get("responses", {})
    for status, response in responses.items():
        if not status.startswith("2"):
            continue
        ref = _json_schema_ref(response.get("content", {}))
        lines.append(f"**Success:** `{status}` " + (f"→ `{ref}`" if ref else "(no body)"))
        lines.append("")
    errors = [
        f"`{status}` {r.get('description', '')}"
        for status, r in responses.items()
        if not status.startswith("2")
    ]
    if errors:
        lines += ["**Errors:** " + " · ".join(errors), ""]
    lines += ["```bash", _curl(method, path, op, schemas), "```", ""]
    return lines


def _response_schemas(spec: dict[str, Any]) -> list[str]:
    names: list[str] = []
    for ops in spec["paths"].values():
        for op in ops.values():
            for response in op.get("responses", {}).values():
                ref = _json_schema_ref(response.get("content", {}))
                if ref and ref not in names:
                    names.append(ref)
    return names


def render(spec: dict[str, Any]) -> str:
    schemas: dict[str, Any] = spec.get("components", {}).get("schemas", {})
    lines = [HEADER]
    for path, ops in spec["paths"].items():
        for method, op in ops.items():
            lines += _endpoint(method, path, op, schemas)
    lines += ["## Response schemas", ""]
    nested = ["Author"]
    for name in [*_response_schemas(spec), *nested]:
        lines += _schema_table(name, schemas)
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    source = Path(sys.argv[1] if len(sys.argv) > 1 else "../docs/openapi.json")
    target = Path(sys.argv[2] if len(sys.argv) > 2 else "../docs/api.md")
    content = render(json.loads(source.read_text(encoding="utf-8")))
    target.write_text(content, encoding="utf-8", newline="\n")
    print(f"Wrote {target}")  # noqa: T201 - CLI output


if __name__ == "__main__":
    main()
